const express = require('express')
const mangaRouter = express.Router()
const mangaController = require('../controller/manga-controller')
const authenticate = require('../middlewares/authenticate')
const upload = require('../middlewares/upload')

mangaRouter.post("/",authenticate.auth,upload.single('imageUrl'),mangaController.titlePost)
mangaRouter.get("/myManga",authenticate.auth,mangaController.getManga)
mangaRouter.delete("/myManga/:id",authenticate.auth,mangaController.deleteManga)
mangaRouter.post("/myManga/:id/Chapter",authenticate.auth,upload.array("images",20),mangaController.postChapter)
mangaRouter.put("/myManga/:id/Chapter/:chapterNo",authenticate.auth,upload.array("images",20),mangaController.editChapter)
mangaRouter.delete("/myManga/:id/Chapter/:chapterId",authenticate.auth,mangaController.deleteChapter)
mangaRouter.get("/myManga/:id/Chapter/:chapterNo/pages",mangaController.getAllPages)
mangaRouter.get("/myManga/:id/Chapter",mangaController.getAllChapter)
mangaRouter.get("/myManga/all",mangaController.getAllManga)
mangaRouter.get("/search",mangaController.searchManga)
mangaRouter.get("/getMangaPagination/",mangaController.getMangaPagination)
mangaRouter.patch("/:mangaId/increment-views",mangaController.increaseViews)
module.exports = mangaRouter
