const express = require('express')
const app = express()
const cors = require("cors")
const authRouter = require('./Routes/auth-routes')
const errorHandler = require('./middlewares/error')
const notFound = require('./middlewares/notFound')
const mangaRouter = require('./Routes/manga-routes')
const favoriteRouter = require('./Routes/favorite-routes')
require('dotenv').config()
const multer = require('multer')
const morgan = require("morgan")
const adminRouter = require('./Routes/admin-routes')
app.use(express.json())
app.use(cors())
app.use("/auth", authRouter)
app.use("/manga",mangaRouter)
app.use("/favorite",favoriteRouter)
app.use("/admin",adminRouter)
app.use(morgan())
app.use(errorHandler)
app.use('*',notFound)
const port = process.env.PORT || 8000
app.listen(port,()=> console.log(`Server is running ${port}`))